CREATE TABLE Employee (
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE,
    DEPARTMENT VARCHAR(50)
);

INSERT INTO Employee (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES 
('John', 'Abraham', 1000000.00, '2013-01-01', 'Banking'),
('Michael', 'Clarke', 800000.00, '2013-01-01', 'Insurance'),
('Roy', 'Thomas', 700000.00, '2013-02-01', 'Banking'),
('Tom', 'Jose', 600000.00, '2013-02-01', 'Insurance'),
('Jerry', 'Pinto', 650000.00, '2013-02-01', 'Insurance'),
('Philip', 'Mathew', 750000.00, '2013-01-01', 'Services'),
('Towino', 'Thomas', 650000.00, '2013-01-01', 'Services'),
('Leffin', 'Jose', 600000.00, '2013-02-01', 'Insurance');


SELECT * FROM Employee;
SELECT FIRST_NAME, LAST_NAME from Employee;
SELECT UPPER(FIRST_NAME) as FIRST_NAME from Employee;
SELECT LOWER(FIRST_NAME) as FIRST_NAME from Employee;
SELECT DISTINCT DEPARTMENT from Employee;
SELECT SUBSTRING(FIRST_NAME,1,3) as F_FIRST_NAME from Employee;
SELECT INSTR(FIRST_NAME, 'o') as johnname from Employee where FIRST_NAME = "John";
SELECT RTRIM(FIRST_NAME) as FIRST_NAME_rspace from Employee;
SELECT LTRIM(FIRST_NAME) as FIRST_NAME_lspace from Employee;
SELECT LENGTH(FIRST_NAME) as FIRST_NAME_len from Employee;
SELECT REPLACE(FIRST_NAME, 'o', '$') as FIRST_NAME_modif from Employee;
SELECT FIRST_NAME || '_' || LAST_NAME as FULL_NAME from Employee;
SELECT FIRST_NAME, YEAR(JOINING_DATE) AS Joining_Year, MONTH(JOINING_DATE) AS Joining_Month, DAY(JOINING_DATE) AS Joining_Day FROM Employee;
FROM SELECT LENGTH(FIRST_NAME) as FIRST_NAME_len from Employee;
SELECT * from Employee order by first_name asc;
SELECT * from Employee order by first_name desc;
SELECT * from Employee order by SALARY desc;
SELECT * from Employee where first_name in('John' ,'Roy');
SELECT * FROM Employee WHERE FIRST_NAME NOT IN ('John', 'Roy');
SELECT * FROM Employee WHERE LENGTH(FIRST_NAME) = 4    
SELECT * from Employee WHERE LENGTH(FIRST_NAME) = 4 AND RIGHT(FIRST_NAME,1 = 'J');
SELECT * FROM Employee WHERE SALARY > 600000;
SELECT * FROM Employee WHERE SALARY BETWEEN 500000 AND 800000;
SELECT * from Employee where first_name in('John' ,'Michael');
SELECt * FROM Employee WHERE YEAR(JOINING_DATE) = 2013;
SELECt * FROM Employee WHERE MONTH(JOINING_DATE) = 1;
SELECt * FROM Employee WHERE JOINING_DATE < '2013-01-01';
ALTER TABLE Employee ADD COLUMN Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
SELECT * FROM Employee;
SELECT JOINING_DATE, TIME FROM Employee;
ALTER TABLE Employee ADD COLUMN Employee_Id INT AUTO_INCREMENT PRIMARY KEY;



CREATE TABLE Incentives (
    EMPLOYEE_REF_ID INT,
    INCENTIVE_DATE DATE,
    INCENTIVE_AMOUNT DECIMAL(10, 2)
);

INSERT INTO Incentives (EMPLOYEE_REF_ID, INCENTIVE_DATE, INCENTIVE_AMOUNT) VALUES 
(1, '2013-01-01', 5000.00),
(2, '2013-01-01', 3000.00),
(3, '2013-02-01', 4000.00),
(4, '2013-02-01', 4500.00),
(5, '2013-02-01', 4500.00),
(6, '2013-01-01', 3500.00);

SELECT * FROM Incentives;


SELECT e.EMPLOYEE_ID, e.JOINING_DATE, i.INCENTIVE_DATE, DATEDIFF(i.INCENTIVE_DATE, e.JOINING_DATE) AS DATE_DIFFERENCE
FROM Employee e
JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT * FROM Employee WHERE LAST_NAME LIKE '%n' ESCAPE '\\';
SELECT REPLACE(LAST_NAME, '[^a-zA-Z0-9]+', ' ') AS Clean_Last_Name FROM Employee;
SELECT DEPARTMENT, AVG(SALARY) FROM Employee GROUP BY DEPARTMENT ORDER BY AVG(SALARY) ASC;
SELECT DEPARTMENT, MAX(SALARY) FROM Employee GROUP BY DEPARTMENT ORDER BY MAX(SALARY) ASC;
SELECT DEPARTMENT, MIN(SALARY) FROM Employee GROUP BY DEPARTMENT ORDER BY MIN(SALARY) ASC;
SELECT YEAR(JOINING_DATE) AS Join_Year, MONTH(JOINING_DATE) AS Join_Month, COUNT(*) AS Num_of_Employees
FROM Employee
GROUP BY Join_Year, Join_Month
ORDER BY Join_Year, Join_Month;

SELECT DEPARTMENT, SUM(SALARY) AS Total_Salary FROM Employee GROUP BY DEPARTMENT
HAVING Total_Salary > 800000
ORDER BY Total_Salary DESC;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT
FROM Employee e
JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT
FROM Employee e
JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID
WHERE i.INCENTIVE_AMOUNT > 3000;


SELECT e.FIRST_NAME, COALESCE(i.INCENTIVE_AMOUNT, 0) AS Incentive_Amount
FROM Employee e
LEFT JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT e.FIRST_NAME, i.INCENTIVE_AMOUNT
FROM Employee e
LEFT JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID
WHERE i.INCENTIVE_AMOUNT IS NOT NULL;

SELECT e.FIRST_NAME,
       (SELECT MAX(INCENTIVE_AMOUNT)
        FROM Incentives
        WHERE EMPLOYEE_REF_ID = e.EMPLOYEE_ID) AS Max_Incentive
FROM Employee e;

SELECT SALARY FROM Employee ORDER BY SALARY DESC LIMIT 2;
SELECT SALARY FROM Employee ORDER BY SALARY DESC LIMIT 1 OFFSET 1;
SELECT FIRST_NAME AS Name FROM Employee UNION ALL SELECT LAST_NAME AS Name FROM Employee;

SELECT e.*
FROM Employee e
INNER JOIN Incentives i ON e.EMPLOYEE_ID = i.EMPLOYEE_REF_ID;

SELECT 
    FIRST_NAME,
    LAST_NAME,
    CASE 
        WHEN FIRST_NAME = 'John' THEN SALARY * 0.2
        WHEN FIRST_NAME = 'Roy' THEN SALARY * 0.1
        ELSE SALARY * 0.15
    END AS Percentage_of_Salary
FROM Employee;

SELECT 
    CASE WHEN DEPARTMENT = 'Banking' THEN 'Bank Dept'
         WHEN DEPARTMENT = 'Insurance' THEN 'Insurance Dept'
         WHEN DEPARTMENT = 'Services' THEN 'Services Dept'
    END AS Department
FROM Employee;


UPDATE Incentives i
JOIN Employee e ON i.EMPLOYEE_REF_ID = e.EMPLOYEE_ID
SET i.INCENTIVE_AMOUNT = 9000
WHERE e.FIRST_NAME = 'John';

DELETE Employee
FROM Employee
INNER JOIN Incentives ON Employee.EMPLOYEE_ID = Incentives.EMPLOYEE_REF_ID;
SELECT * FROM Employee;
